name: CodeSentinel PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CodeSentinel
        uses: Akpguj/CodeSentinel@main
        with:
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          # openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          # groq_api_key: ${{ secrets.GROQ_API_KEY }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # hf_token: ${{ secrets.HF_TOKEN }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          # OPENAI_BASE_URL: https://openrouter.ai/api/v1
